### ISSUE TITLE
Shortcode webcomic_list_characters doesn't seem to work

### ISSUE THREAD

**Issue by metafarion** [mgsisk/webcomic#240]
Although [webcomic_dropdown_characters] produces the correct content, [webcomic_list_characters] on the same page just comes out as plain text

To be absolutely sure, I switched back to vanilla Inkblot and it comes out the same.

**Comment by mgsisk** [comment]
Thanks @metafarion. This is a really stupid bug on my part; until it's fixed, try using `[webcomic_list_character]` instead (I forgot the `s` on the end). This will be fixed in the next Webcomic update, so – whenever that shows up – you'll want to go back to the (technically correct) `[webcomic_list_characters]`.

**Comment by mgsisk** [comment]
Fixed in 4.3.1
