### ISSUE TITLE
Webcomic Nav w/Selling Prints

### ISSUE THREAD

**Issue by CAMorgan** [mgsisk/webcomic#257]
Firstly, happy new year!

I'm currently customising a theme at http://leylinescomic.com/
They want to sell the original art for their comic page. When the option is selected, navigation is fine. (See here: http://leylinescomic.com/leylines/c11p53-fakes/ )

When we deselect selling, all the navigation buttons float left. (http://leylinescomic.com/leylines/c11p54-something-else/)

Is there a way to mark a page as "sold" and have it display a sold image?
If there is a page that isn't selling its original art, is it possible to have the navigation aligned evenly?

**Comment by mgsisk** [comment]
Happy New Year, @CAMorgan!

The bad news is that, you'll need to edit a core Webcomic file to get this working properly. The good news is that it really ought to work this way *anyway*, so you shouldn't have to worry about updates messing with this change as I'm planning on making it directly to Webcomic now that you've pointed it out.

Find lines 1340–1342 in `webcomic/-/php/widgets.php`:

```php
if ( $output = WebcomicTag::purchase_webcomic_link( '%link', $link, get_the_ID() ) ) {
	echo $before_widget, empty( $title ) ? '' : $before_title . $title . $after_title, $output, $after_widget;
}
```

And remove lines 1340 and 1342, so that only the `echo…` line remains:

```php
echo $before_widget, empty( $title ) ? '' : $before_title . $title . $after_title, $output, $after_widget;
```
That should force the Purchase Webcomic Link widget to *always* output something, which will force the nav links to line up wether or not there's an actual purchase link there or not.

**Comment by CAMorgan** [comment]
Thanks for the feedback! I gave it a try and nothing changed except now if I have selling original art/prints enabled it doesn't display.

**Comment by mgsisk** [comment]
Ah, that's entirely my fault. Just above the `echo…` line, try adding this:

```php
$output = WebcomicTag::purchase_webcomic_link( '%link', $link, get_the_ID() );
```

**Comment by CAMorgan** [comment]
Got the purchase button back now, ha, but still no alignment happening for the navigation buttons.

**Comment by mgsisk** [comment]
Interesting… try changing the `$output…` line to this:

```php
$output = WebcomicTag::purchase_webcomic_link( '%link', $link, get_the_ID() ) ?: '<br>';
```

**Comment by CAMorgan** [comment]
Now it works, excellent!
I have a few questions about the purchase print option itself, is it ok to ask here or should I open a new thread?

**Comment by mgsisk** [comment]
Go ahead and open a new thread (or multiple threads); I'll close this one.
