### ISSUE TITLE
Selling Prints/Original Comics Questions

### ISSUE THREAD

**Issue by CAMorgan** [mgsisk/webcomic#258]
Hi, again!

I'd like to ask a few questions about the Selling Comics option for the Webcomic plugin. I've gone through the FAQ available, and didn't find what I was looking for.

1) Does the "Sell Prints" option need to be checked in order to sell an original comic page? When I only have "original" selected, nothing appears in my webcomic's navigation widget that lets anyone click on to get to the purchase page.

2) I was going to ask about setting the prices for prints/originals but it seems to operate on +/- increments, so nevermind.

3) How is a comic marked as sold??

**Comment by mgsisk** [comment]
1. Yes, **Sell Prints** must be checked in order to sell the original comic page. You can, however, only offer an option to buy the original (without other print options).
2. Correct. Every comic in a collection uses the same default pricing (set on the Collection Settings page), but you can adjust each comic's print price individually by setting an adjustment rate for the domestic, international, and original prices and shipping.
3. Webcomic uses [PayPal's IPN's](https://developer.paypal.com/webapps/developer/docs/classic/products/instant-payment-notification/) to track purchases. PayPal generates an Instant Payment Notification (IPN) and sends it back to your site to a Webcomic-specific URL (something like http://example.com/?webcomic_commerce_ipn) whenever someone tries to purchase a comic print using a Webcomic-generated purchase link. Webcomic then verifies that the IPN and – if everything looks good – will remove the original print option so that it can't be sold more than once (if the user was trying to buy an original print). Webcomic logs all IPN's – regardless of the type of sale or wether or not it succeeded – which you can view on the **Tools > Webcomic Commerce** admin page.

**Comment by CAMorgan** [comment]
Okay, that information is good to know, but now I have a problem. No matter how I alter the settings, the pricing options for purchasing prints still show instead of just for buying the original art. This page is used as an example: http://leylinescomic.com/leylines/c11p53-fakes/prints/

![untitled-1](https://cloud.githubusercontent.com/assets/6171593/12219716/9c670176-b704-11e5-8265-8d3be701591e.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/6171593/12219715/9c652ed2-b704-11e5-8a82-aa1f05c90507.jpg)
![untitled-3](https://cloud.githubusercontent.com/assets/6171593/12219717/9c67591e-b704-11e5-857f-5e44506c9f09.jpg)
