### ISSUE TITLE
Modify HTML output by webcomic_list_<term>

### ISSUE THREAD

**Issue by metafarion** [mgsisk/webcomic#273]
How would one go about editing the character list beyond the provided arguments.

In my case I'm looking to make some changes to the character list like:
a) Remove the link from each item, leaving just a plain list.
b) Change the order of the elements, putting the image first, then the title, then the description.
c) Give a unique id or anchor name to each list item so they can be jumped to from a character nav at the top of the page.

**Comment by ashikai** [comment]
IDK about A and C as I'm having a similar problem with those, but I can help with B at least.

When the template tag outputs the character information it wraps each element in it's own html tags, so essentially you can use CSS to position the elements the way you want to. Try something like:

`.webcomic-term{
	list-style:none;
	overflow:hidden;
	display:block;
	clear:both;
}`
This is the container for a single characters data. Make sure to add your own width and height parameters! I have the clear:both; parameter used here because I had my container take up the full width and stack like a list on top of each other. If you want to display it more as a grid, change display:block; to display:inline-block;.

	`.webcomic-term-image{
		width:27%;
		display:block;
		float:left;
	}`
This styles the image for each character. This is the image's CONTAINER, not the image itself, so the width parameter here will not resize the image. Float:left; will display it on the left hand side.

	`.webcomic-term-name, .webcomic-term-description{
		display:block;
		float:right;
		width:70%;
	}`
This styles both the title/name and the description together.  Floating them right will put them on the right side stacked on top of each other. They'll only stack if they both have the same width though.

You'll end up with something that looks kinda like this (assuming that grey box is the image):
![d5fab01a6930a47d3428cffe1349a98288ef0ed2d2b74c2c09 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/4002258/17638317/4aca8574-60b7-11e6-97c3-0dfab2e316e4.png)

It's a little hack-y but it works! Hope that helped! <3

**Comment by mgsisk** [comment]
Hey @metafarion! All three of those can be done with a custom Walker; I've just posted an example of how that would look in #277.
