### ISSUE TITLE
Navigation Placement

### ISSUE THREAD

**Issue by ericandabear** [mgsisk/webcomic#276]
I am editing www.dogstarcomic.com and having trouble with the navigation buttons being placed.
I have noticed that on the older pages I uploaded, I had the navigation at the top, whereas I have since moved them to the bottom, and the pages uploaded prior to this change have the navigation remaining at the top. This is fine unless its a glitch, I plan on deleting all posts and pages when I begin uploading the actual comic.

My problem is that both the header image and the navigation buttons nestled inside the page-posts refuse to align to the center. They are both awkwardly aligned left.
I am not sure if it has something to do with my wordpress installation, but I am unable to edit the actual wordpress theme, because:
"You need to make this file writable before you can save your changes. See the Codex for more information." 
So I have been using a plugin called "Custom CSS" to add code, but nothing I have written has been able to adjust the alighment of the navigation nor the header image.
Please help if you can!

**Comment by mgsisk** [comment]
Hey @ericandabear. You're on the right track; the issue is with the CSS. You can actually add custom CSS directly to Inkblot through the WordPress Customizer (it should be at the very bottom); try adding this there (or in the Custom CSS plugin):

```css
.widgets.webcomic-header,
.widgets.webcomic-footer {
  text-align: center;
}
```
The `You need to make this file writable before you can save your changes. See the Codex for more information.` is a file permission issue; you may need to access your site via FTP and edit the file permissions on the theme (they should be 644 or 755).

The navigation position (top for older posts, bottom for newer posts) appears to be an attachment issue. It looks like earlier posts have the image inserted directly into the post content, which – for Webcomic posts, at least – is not necessary. You just have to attach the image to the post (this happens automatically when you upload an image on the Add/Edit Post page), and it should show up in the more typical spot (with navigation below the comic).

**Comment by ericandabear** [comment]
Awesome, thanks! That fixed it the navigation alignment!

I played with the attachment of the media files to the posts, and ultimately found that if I uploaded the pages with the media uploader in the "new post" form, it would post twice; once in the media section, and once inside the post itself. I had been deleting the one in the posts and it seemed to solve the issue (assuming I remember to do it each time) but if there is a way to keep this from happening I am willing to learn!
