### ISSUE TITLE
Shortcodes Not Working

### ISSUE THREAD

**Issue by FINGL0NGER** [mgsisk/webcomic#291]
I have a static front page and I'm trying to add a thumbnail link to the last webcomic. I try the shortcode "[last_webcomic_link link="%thumbnail"]" but nothing shows up.
http://test.red-oasis.com/

I have other shortcode plugins installed that all work fine, but Webcomic's shortcodes aren't working at all. I even tried disabling all the other plugins, but that didn't work.

**Comment by mgsisk** [comment]
Hm… assuming your comic has an image attached (if it doesn't, that shortcode won't display anything because there's no `%thumbnail` to display), there are at least two other things you could check/try:

1. Specify a collection for the page in the Webcomic Collection meta box on the Edit Page screen.
2. Specify a collection directly in the shortcode, like `[last_webcomic_link link="%thumbnail" collection="webcomic1"]

**Comment by FINGL0NGER** [comment]
Option 2 did it. Thank you.

**Comment by FINGL0NGER** [comment]
Slightly related to this, is there any way to display a given webcomic's featured image instead of a thumbnail?
