### ISSUE TITLE
Permalinks structure help

### ISSUE THREAD

**Issue by dahliadahlia** [mgsisk/webcomic#302]
Hello! I'm just dipping my toes into the Webcomic plugin and I can't quite get my permalinks to work the way I want them to.

### Expected Behavior
Visit front page of site: mywebcomic.com, shows the most recent comic.
Visit another comic page: mywebcomic.com/name-of-comic-page

### Current Behavior
Visit another comic page: mywebcomic.com/webcomic-name/name-of-webcomic-page

### Context
I'm working with a single collection, so I'm trying to make the urls as neat as possible. When viewing comics, it forces the webcomic collection name/slug into the url. I can't leave the "Single webcomic slug" portion of the permalinks blank.

### Environment
4.4.1 - Webcomic 
4.9.2 - WordPress
7.1 - PHP

**Comment by mgsisk** [comment]
Unfortunately, what you're seeing is how WordPress handles custom post type permalink's; there's no reliable way to remove the `webcomic-name` prefix (without breaking other parts of WordPress, at least). The best you could do is use an extremely short prefix, like `_` or `c`, but – since it's mandatory – something like `comic` or `page` (a short but recognizable word) might be more user-friendly.
