### ISSUE TITLE
Sidebars Disappeared - Webcomic 5.0

### ISSUE THREAD

**Issue by CAMorgan** [mgsisk/webcomic#303]
Hi Mike!

I just upgraded to Webcomic 5.0 and I'm using Wordpress 4.9.2. Sidebars disappeared on all of my regular pages except for my homepage at http://tdugn.com/

Other pages such as http://tdugn.com/archive/ show the issue.

The theme I'm using is Inkblot 4.5.2 and I'm currently using PHP 7 on the server. I ran a debug on one of the affected pages, see below:

---
Debug This Mode: sidebars-current - All instances of get_sidebar() and dynamic_sidebar() in the current template

Current Template: /home2/ealaiont/public_html/tdugn/wp-content/themes/inkblot/page.php
Array
(
    [0] => get_sidebar('; get_footer') Missing sidebar template for ; get_footer.php
)
---

Any help is appreciated.

**Comment by mgsisk** [comment]
Apologies for the trouble @CAMorgan. Based on the debug output, it looks like there's an issue in Inkblot's `page.php` template. Can you confirm that the last line in `/wp-content/themes/inkblot/page.php` is:

```php
<?php get_sidebar(); get_footer();
```
or try changing the last line to that and see if that corrects the issue?

**Comment by CAMorgan** [comment]
I just checked and that is indeed the last line.

**Comment by mgsisk** [comment]
Hm… can you try removing the call to get_sidebar(); from that file so that the last line is just:

```php
<?php get_footer();
```

That won't get the sidebars back, obviously, but I'm hoping it will at least get the footer to load. Looking at your pages there's definitely an error somewhere in that area that's preventing both `get_sidebar()` and `get_footer()` from working.

**Comment by CAMorgan** [comment]
I gave it a try and there's no change. Footer and sidebars still gone.

**Comment by mgsisk** [comment]
Strange; could you email me your theme (both Inkblot and your child theme, if any)? If I can duplicate this on my dev box that might help me find the issue.

**Comment by CAMorgan** [comment]
Certainly! Just emailed to you.

**Comment by mgsisk** [comment]
Thanks @CAMorgan; unfortunately, I'm still at a loss. Just for kicks, can you try creating a file named `; get_footer` in your theme directory?

**Comment by CAMorgan** [comment]
I made the file in my theme directory. I also set up a login for you just in case you needed to get in. You should've received an email.

**Comment by mgsisk** [comment]
Thanks @CAMorgan, admin access helped. The issue is with the `Mgsisk\Webcomic\Restrict\hook_comic_comments` function; it requires a `string` argument, but a `null` value was being passed. I've corrected this on your site and will add a fix for the next release (really that argument *should* always be a string, but WordPress being WordPress…).

**Comment by mgsisk** [comment]
As a quick fix for others having similar issues, open up `/wp-content/plugins/webcomic/src/lib/restrict/common.php` and edit line 180:

```php
function hook_comic_comments( string $template ) : string {
```
to this:

```php
function hook_comic_comments( $template ) {
```
