### ISSUE TITLE
Shortcodes docs

### ISSUE THREAD

**Issue by dels78** [mgsisk/webcomic#306]
Hi!

Thanks a lot for the great plugin, it is exactly what I was hoping to find to manage our comics!

I do however have a little bit of a hard time with integrating with my theme. I know php but I am rusty and not the best at following the wordpress flow of pages and all, and would prefer not to have to edit the code of the theme if at all possible to be able to seamlessly update the different components.

I was able to integrate the Universal way, but to be able to use it the way it works now I would need to be able to click on the image to link to the "webcomic post" page so the comment section appears.

Another (most likely the best for me) way would be to use the shortcodes inside a code box in WPBakery visual pagebuilder, but I find myself unable to get the appropriate parameter tokens to display what I want.

The intent is to have the last comic appear in the area of the wpbakery visual pagebuilder code block, with the navigation links (first, previous, random, next, last), and same as described above, be able to click on the webcomic media that is displayed to go to its "webcomic post" page to see/add comments.

Could you please write the shortcodes and the parameters that I would need? I have read all of the wiki pages, and a lot of the questions here, but I can't find the information on my own.

Thanks!

**Comment by mgsisk** [comment]
Hey @dels78, thanks for using Webcomic! I'm not entirely sure how WPBakery works, but I believe this will get you the basic setup you're looking for:

```
[webcomic_link][webcomic_media][/webcomic_link]
[first_webcomic_link] [previous_webcomic_link] [next_webcomic_link] [last_webcomic_link]
```

The first will display the current comic's media, linked to it's single-comic page, while the second line will display the standard f/p/n/l comic navigation links. You might need to add some additional HTML or CSS to get them styled exactly how you want.

**Comment by dels78** [comment]
@mgsisk Thank you, I had tried this and unfortunately it didn't work as is.

I have obfuscated the url and the actual links, but the only thing that pops up is the links to first and last... even random works fine... but the "current" links or media are not showing at all, is there a way to specify that I want the media from the last comic in the shortcode?

**Comment by mgsisk** [comment]
Hm… it looks like Muffin Builder is part of a (or several) premium theme(s), unfortunately, but I think I understand what's going on now. This should get you close:

```
[last_webcomic_link]%full[/last_webcomic_link]
[first_webcomic_link] [last_webcomic_link]
```

But – at the moment – what you're trying to do probably won't work with the `[previous_webcomic_link]` and `[next_webcomic_link]` shortcodes. The problem is that those shortcodes need a point of reference to decide what's "previous" and what's "next", but the only way to specify a reference (currently) is to provide a post ID. You could hardcode it, like:

```
[previous_webcomic_link post="1234"]
```
But then you'd have to update it every time you publish a new comic. I'll have to think about this one for a bit… I'm not sure if there's a good alternative to this.
