### ISSUE TITLE
Hamburger menu issues

### ISSUE THREAD

**Issue by pixel-prism** [mgsisk/webcomic#313]
Hello, again! So, for the Primary Menu up top, when it goes to mobile layout, two things go wrong: the item it's chosen to keep out of the menu is on a separate line from the hamburger icon, below it; and the hamburger icon doesn't do anything when clicked. Instead, the menu comes up from the title menu item.

### Expected Behavior
When you click a hamburger menu, you expect the menu to expand into clickable menu items. Also, if there's one item outside of the menu, I expect it to be on the same line as the hamburger icon.

### Current Behavior
Right now, when you click on the hamburger menu, nothing happens. However, when you click the item (which seems to change depending on the page you're on; the home has New Readers while the other pages have the title of the page you're on) it DOES bring up the menu. New Readers is inaccessible from Home (links to the menu) but from any other page, it links to the New Readers page.

### Context
For those visiting the site via mobile, it's confusing that you can't bring up the menu from the hamburger icon, and folks may think you can't access the rest of the site.

### Example
As per usual (haha ;;; ), you can see the live example at http://cvilbrandt.naiya.org

### Environment
- Webcomic 5.0.5
- WordPress 4.9.6
- PHP 7.0.30
- Chrome 66.0.3359.158 on Android 8.0.0, Samsung Galaxy S8.

**Comment by mgsisk** [comment]
There a couple of different things going on with the site menu.

First, it looks like there's a `display: flex` rule on `#menu-primary-menu` that's overriding Inkblot's default responsive styles and pushing the mobile version of the menu down. Try adding this to your custom CSS:
```css
@media only screen and (max-width: 800px) { /* Or whatever your responsive width is */
  #menu-primary-menu {
    display: none; /* completely hide the standard menu on mobile devices */
  }
}
```
That will get the mobile menu and the hamburger icon almost lined up (the hamburger icon in Inkblot is actually an illusion; it's supposed to sit right over the `<select>` menu, so that when you "click" the hamburger icon you're actually hitting the `<select>` menu). To get them lined up properly, try adding this to your custom CSS:

```css
.banner select {
  padding: 0.5rem 1rem;
}
```
To avoid having the New Reader option pre-selected on the homepage you'll need to add an extra item, empty item to the menu so that there's something else for it to default to. Open up `/inkblot/header.php` and changes line 55 and 59:

```php
'items_wrap' => '<select>%3$s</select>', // line 55
…
print '<select>'; // line 59
```
to

```php
'items_wrap' => '<select><option></option>%3$s</select>', // line 55
…
print '<select><option></option>'; // line 59
```
That should prevent the New Reader option from being selected by default on the homepage.

**Comment by pixel-prism** [comment]
You are so kind for taking the time to help me with these issues. Thank you so much! It worked great!
